### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [TetraSomia/Rasterizer#3]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/113877720-8d613980-97eb-11eb-9c85-8a85ace626c3.png)

thank you  
best regards to you  
William

**Comment by TetraSomia** [comment]
Hello William,
Sorry for the delay, I added the liblapin as a submodule so you can directly get the correct version.
Don't forget to clone with the `--recurse-submodules` option and to download the SFML library (`sudo apt install libsfml-dev`).
Best regards !
